### ISSUE TITLE
Listing on Mailspring Community?

### ISSUE THREAD

**Issue by CodeMouse92** [asparc/ui-predawn#1]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme listed there: https://community.getmailspring.com/c/themes/9

**Comment by asparc** [comment]
Hi CodeMouse! I'm happy to hear that the development efforts for Mailspring have been resumed! It would be my pleasure to list my theme on Discourse. I submitted a membership request for @theme_dev.

**Comment by asparc** [comment]
It took a while, but it's listed among the themes in the Mailspring community now!
